config/routes.rb
require 'sidekiq-scheduler/web'
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users

  defaults format: :json do
    namespace :api do
      resources :book_stocks, only: [:index, :create, :update, :destroy]
      resources :books, only: [:index]
    end
  end

  resource :dashboard, only: [:show]
  resources :books, only: [:index]

  root to: "landing_pages#show", as: :landing_page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_stocks, dependent: :destroy

  validates :title, presence: true
end

app/models/book_stock.rb
class BookStock < ApplicationRecord
  belongs_to :book_store
  belongs_to :book

  validates :stock_level, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_in_stock_to_reflect_stock_level!
    update(in_stock: !stock_level.zero?)
  end
end

app/models/book_store.rb
class BookStore < ApplicationRecord
  has_many :book_stocks, dependent: :destroy
  has_many :books, through: :book_stocks
  has_many :users

  validates :name, presence: true

  before_destroy :remove_foreign_key_from_users

  private

  def remove_foreign_key_from_users
    users.update_all book_store_id: nil
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  devise :database_authenticatable, :lockable, :rememberable, :validatable

  belongs_to :book_store, optional: true
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
    include ActionController::Caching
    acts_as_token_authentication_handler_for User

    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :respond_with_forbidden
    rescue_from ActiveRecord::RecordNotFound, with: :respond_with_not_found

    private

    def respond_with_forbidden(error)
      render json: { message: error.message }, status: :forbidden
    end

    def respond_with_not_found(error)
      render json: { message: error.message }, status: :not_found
    end
  end
end

app/controllers/api/book_stocks_controller.rb
module Api
  class BookStocksController < ApplicationController
    def index
      @book_stocks = policy_scope(BookStock).all
    end

    def create
      @book_stock = BookStock.new(book_stock_params)
      @book_stock.book_store = current_user.book_store

      authorize @book_stock

      if @book_stock.save
        render :show
      else
        render json: @book_stock.errors.messages, status: :unprocessable_entity
      end
    end

    def update
      @book_stock = BookStock.find(params[:id])

      authorize @book_stock

      if @book_stock.update(book_stock_params)
        render :show
      else
        render json: @book_stock.errors.messages, status: :unprocessable_entity
      end
    end

    def destroy
      @book_stock = BookStock.find(params[:id])

      authorize @book_stock

      @book_stock.destroy

      render json: { message: "success" }
    end

    private

    def book_stock_params
      params.require(:book_stock).permit(:book_id, :stock_level, :in_stock)
    end
  end
end

app/controllers/api/books_controller.rb
module Api
  class BooksController < ApplicationController
    skip_before_action :authenticate_user_from_token!

    def index
      @books = policy_scope(Book).all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    books = policy_scope(Book).all

    rows = books.map do |book|
      [
        book.id,
        book.title,
        book.created_at.strftime("%e/%m/%Y %l:%M:%S %p"),
        book.updated_at.strftime("%e/%m/%Y %l:%M:%S %p")
      ]
    end

    @table_data = {
      title: "All Books",
      search_input_placehodler: "Search among #{books.length} #{"book".pluralize(books.length)}",
      searchable_row_index: 1,
      headers: ["id", "title", "created at", "updated at"],
      rows: rows
    }
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @user = current_user

    book_stocks = policy_scope(current_user.book_store.book_stocks).all.includes(:book)

    rows = book_stocks.map do |book_stock|
      [
        book_stock.id,
        book_stock.book.title,
        book_stock.stock_level,
        book_stock.in_stock,
        book_stock.created_at.strftime("%e/%m/%Y %l:%M:%S %p"),
        book_stock.updated_at.strftime("%e/%m/%Y %l:%M:%S %p")
      ]
    end

    @table_data = {
      title: "Books in Stock",
      search_input_placehodler: "Search among #{book_stocks.length} #{"book".pluralize(book_stocks.length)}",
      searchable_row_index: 1,
      headers: ["id", "book", "stock level", "in stock", "created at", "updated at"],
      rows: rows
    }
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  skip_before_action :authenticate_user!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<%= render "shared/navbar" %>

<div class="max-w-screen-2xl mx-auto px-4 pt-0.5">
  <%= render partial: "shared/styled_table", locals: { data: @table_data } %>
</div>

app/views/dashboards/show.html.erb
<%= render "shared/navbar" %>

<div style="background-color: var(--gray);" class="pb-10 mb-2">
  <div class="max-w-screen-2xl mx-auto px-4 pt-0.5">
    <h3 class="my-4 font-header text-xl text-black text-opacity-90 font-bold">Credentials</h3>
    <div style="height: 0.0625rem;" class="bg-gray-300 mb-4"></div>

    <ul class="text-md text-black text-opacity-75 font-medium">
      <li class="flex items-baseline mb-1">
        <div style="color: var(--light-blue);" class=" w-36">API Key: </div>
        <div class="text-black text-opacity-100"><%= @user.authentication_token %></div>
        <div data-controller="clipboard" data-clipboard-copy="<%= @user.authentication_token %>">
          <div
            style="color: var(--light-blue)"
            class="ml-2 text-xs underline opacity-80 cursor-pointer"
            data-action="click->clipboard#copy"
            data-clipboard-target="button"
          >copy to clipboard</div>
        </div>
      </li>
      <li class="flex items-baseline mb-1">
        <div style="color: var(--light-blue);" class=" w-36">Email: </div>
        <div><%= @user.email %></div>
      </li>
      <li class="flex items-baseline mb-1">
        <div style="color: var(--light-blue);" class=" w-36">Book Store: </div>
        <div><%= @user.book_store&.name %></div>
      </li>
    </ul>
  </div>
</div>

<div class="max-w-screen-2xl mx-auto px-4 pt-0.5">
  <%= render partial: "shared/styled_table", locals: { data: @table_data } %>
</div>

app/views/landing_pages/show.html.erb
<% if user_signed_in? %>
  <p><%= link_to "Go To Dashboard", dashboard_path %></p>
<% else %>
  <p><%= link_to "Sign in", new_user_session_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Shelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", media: "all" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700;900&family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    <p style="background-color: lightgreen;"><%= flash[:notice] %></p>
    <p style="background-color: wheat;"><%= flash[:alert] %></p>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav
  style="background-color: var(--dark-blue); height: 60px;"
  class="flex justify-between px-4"
>
  <div class="flex space-x-7">
    <%= link_to landing_page_path do %>
      <h1 class="mt-4 font-header text-xl text-white font-black text-opacity-100">Book Shelf</h1>
    <% end %>
    <ul class="navlink-list">
      <% if current_page?(dashboard_path) %>
        <li class="navlink-link--current-page">Dashboard</li>
      <% else %>
        <li class="navbar-link"><%= link_to "Dashboard", dashboard_path %></li>
      <% end %>

      <% if current_page?(books_path) %>
        <li class="navlink-link--current-page">All Books</li>
      <% else %>
        <li class="navbar-link"><%= link_to "All Books", books_path %></li>
      <% end %>

      <li class="navbar-link"><%= link_to "Account", "#" %></li>
    </ul>
  </div>

  <div>
    <ul class="navlink-list">
      <li class="navbar-link"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    </ul>
  </div>
</nav>

app/views/shared/_styled_table.html.erb
<div data-controller="searchable-table">
  <div class="my-4 flex space-x-6 items-center">
    <h3 class="font-header text-xl text-black text-opacity-90 font-bold"><%= data.fetch(:title) %></h3>
    <input
      class="h-10 w-80 block px-4 border border-gray-300 border-solid"
      type="text"
      placeholder="<%= data.fetch(:search_input_placehodler) %>"
      data-action="input->searchable-table#filter"
    >
  </div>
  <p class="font-medium mb-4" data-searchable-table-target="resultsSummary"></p>
  <table class="w-full table-auto">
    <thead>
      <tr style="background-color: var(--gray);">
        <% data.fetch(:headers).each do |header| %>
          <th><div class="flex items-center h-9 p-2 text-left overflow-ellipsis whitespace-nowrap font-medium"><%= header %></div></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% data.fetch(:rows).each do |row| %>
        <tr data-searchable-table-target="row" data-searchable-by="<%= row[data.fetch(:searchable_row_index)] %>">
          <% row.each do |cell| %>
            <td><div class="flex items-center h-9 p-2 text-left overflow-ellipsis whitespace-nowrap"><%= cell %></div></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>